# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: myeducator
email: support@myeducator.com
description: > # this means to ignore newlines until "baseurl:"
  Higher education learning resources for business school instructors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://myeducator.com" # the base hostname & protocol for your site
twitter_username: myeducatorllc
# github_username:  jekyll

# Build settings
markdown: kramdown
