---
title: myeducator
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: support@myeducator.com
description: 'Learning resources for higher education instructors.

'
baseurl: ''
url: http://myeducator.com
twitter_username: myeducatorllc
markdown: kramdown
